version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: rlink
    binary: rlink
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/quaywin/rlink/pkg/version.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
